[package]
name = "json"
version = "0.2.1"
description = "JSON parser and stringifier for Motoko"
repository = "https://github.com/Demali-876/json"
keywords = [ "json", "parse", "stringfy", "validate" ]
license = "MIT"

[dependencies]
regex = "1.24.1"
vector = "0.4.1"
test = "2.0.0"