[package]
name = "json"
version = "0.1.0"
description = "JSON parser and stringifier for Motoko"
repository = "https://github.com/Demali-876/json"
keywords = [ "JSON", "parse", "stringfy" ]
license = "MIT"

[dependencies]
regex = "1.24.1"
vector = "0.4.1"
test = "2.0.0"